"""Regenerate deterministic reference data in isolation and compare bytes."""

from __future__ import annotations

import tempfile
from pathlib import Path

from tools.generate_reference_data import build

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ("catalog", "examples", "policies")


def files_under(root: Path) -> dict[str, bytes]:
    result: dict[str, bytes] = {}
    for directory in GENERATED:
        for path in sorted((root / directory).rglob("*")):
            if path.is_file():
                result[path.relative_to(root).as_posix()] = path.read_bytes()
    return result


def main() -> int:
    with tempfile.TemporaryDirectory() as temporary:
        fresh_root = Path(temporary)
        build(fresh_root)
        expected = files_under(ROOT)
        actual = files_under(fresh_root)
    if expected.keys() != actual.keys():
        missing = sorted(expected.keys() - actual.keys())
        extra = sorted(actual.keys() - expected.keys())
        raise SystemExit(
            f"generated file-set mismatch; missing={missing}; extra={extra}"
        )
    changed = sorted(path for path in expected if expected[path] != actual[path])
    if changed:
        raise SystemExit(f"generated bytes differ: {changed}")
    print(f"generated reference data matches ({len(expected)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
